# See https://release-plz.dev/docs/config for supported fields.
[workspace]
# Conventional PR title
pr_name = "chore(release): release ${version}"
# Release PR branch prefix
pr_branch_prefix = "chore/release-plz"
# Always keep changelog updated
changelog_update = true
# Release type
release_type = "prod"
